version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ayan
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: ayan_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./config.yml:/config.yml
      - ./migrations:/migrations
    command: ["/bin/app"]

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    depends_on:
      - db
    entrypoint: [ "/migrate", "-path=/migrations/schema", "-database", "postgres://postgres:root@db:5432/ayan?sslmode=disable", "up" ]

volumes:
  pg_data:
